from typing import Protocol

from domain.models import Memory, MemoryStatus, MemoryStatusFilter, ScoredMemory


class MemoryRepository(Protocol):
    async def save(self, memory: Memory) -> Memory: ...

    async def find_nearest(
        self, domain: str, embedding: tuple[float, ...], limit: int, status_filter: MemoryStatusFilter
    ) -> list[ScoredMemory]: ...

    async def find_by_tags(
        self, domain: str, tags: tuple[str, ...], status_filter: MemoryStatusFilter
    ) -> list[Memory]: ...

    async def find_pinned(self, domain: str) -> list[Memory]: ...

    async def overwrite_content(
        self, memory_id: str, title: str, context: str, embedding: tuple[float, ...]
    ) -> None: ...

    async def mark_superseded(self, memory_id: str, superseded_by: str) -> None: ...

    async def set_status(self, memory_id: str, status: MemoryStatus) -> None: ...

    async def delete(self, memory_id: str) -> None: ...

    async def pin(self, memory_id: str) -> None: ...

    async def unpin(self, memory_id: str) -> None: ...

    async def record_access(self, memory_id: str) -> None: ...
