import os

GOOGLE_CLOUD_PROJECT_ID = os.environ.get("MNEMOSYNE_GOOGLE_CLOUD_PROJECT_ID", "mnemosyne-cb868")
GOOGLE_CLOUD_LOCATION = os.environ.get("MNEMOSYNE_GOOGLE_CLOUD_LOCATION", "asia-east1")
# Gemini 系列模型在 Vertex AI 的可用區域比 embedding 模型窄很多，asia-east1 不支援，
# 獨立設定避免受限於 Firestore/embedding 共用的 GOOGLE_CLOUD_LOCATION。
GEMINI_CLASSIFIER_LOCATION = os.environ.get("MNEMOSYNE_GEMINI_CLASSIFIER_LOCATION", "us-central1")

# 模型名稱依是否設定 GEMINI_API_KEY 連動：走個人 Google AI Studio 訂閱時，
# 用該平台的向量模型（跟 Vertex AI 的 text-multilingual-embedding-002 向量空間不相容，
# 兩者不可混用；切換模型代表既有記憶的 embedding 全部要重新計算，見 CLAUDE.md）。
EMBEDDING_MODEL = "text-embedding-004" if os.environ.get("GEMINI_API_KEY") else "text-multilingual-embedding-002"
GATE_CLASSIFIER_MODEL = "gemini-2.5-flash"

FIRESTORE_ARRAY_CONTAINS_ANY_LIMIT = 10

MEMORIES_COLLECTION_NAME = "memories"
DOMAINS_COLLECTION_NAME = "domains"
GLOBAL_DOMAIN = "global"
SERVER_PORT = 8001

DOMAIN_LIST_CACHE_TTL_SECONDS = 300

LOW_THRESHOLD = 0.85
DEFAULT_IMPORTANCE_SCORE = 5

WEIGHT_RELEVANCE = 0.50
WEIGHT_IMPORTANCE = 0.25
WEIGHT_RECENCY = 0.15
WEIGHT_ACCESS_FREQUENCY = 0.10

DECAY_LAMBDA = 0.0077

ACCESS_FREQUENCY_LOG_CAP = 20

VECTOR_SEARCH_K_DOMAIN = 40
VECTOR_SEARCH_K_GLOBAL = 10

WRITE_GATE_CANDIDATE_LIMIT = 3

SEARCH_MEMORIES_DEFAULT_LIMIT = 3
PINNED_MEMORIES_DEFAULT_LIMIT = 5
