import os

GOOGLE_CLOUD_PROJECT_ID = os.environ.get("MNEMOSYNE_GOOGLE_CLOUD_PROJECT_ID", "mnemosyne-cb868")
GOOGLE_CLOUD_LOCATION = os.environ.get("MNEMOSYNE_GOOGLE_CLOUD_LOCATION", "asia-east1")

EMBEDDING_MODEL = "text-multilingual-embedding-002"
GATE_CLASSIFIER_MODEL = "gemini-2.5-flash"

FIRESTORE_ARRAY_CONTAINS_ANY_LIMIT = 10

MEMORIES_COLLECTION_NAME = "memories"
DOMAINS_COLLECTION_NAME = "domains"
GLOBAL_DOMAIN = "global"
SERVER_PORT = 8001

DOMAIN_LIST_CACHE_TTL_SECONDS = 300

LOW_THRESHOLD = 0.85
DEFAULT_IMPORTANCE_SCORE = 5

WEIGHT_RELEVANCE = 0.50
WEIGHT_IMPORTANCE = 0.25
WEIGHT_RECENCY = 0.15
WEIGHT_ACCESS_FREQUENCY = 0.10

DECAY_LAMBDA = 0.0077

ACCESS_FREQUENCY_LOG_CAP = 20

VECTOR_SEARCH_K_DOMAIN = 40
VECTOR_SEARCH_K_GLOBAL = 10

WRITE_GATE_CANDIDATE_LIMIT = 3

SEARCH_MEMORIES_DEFAULT_LIMIT = 3
PINNED_MEMORIES_DEFAULT_LIMIT = 5
